export const REDUX_SAGA_LOCATION_ACTION_SET_POSITION = 'REDUX_SAGA_LOCATION_SET_POSITION';
export const REDUX_SAGA_LOCATION_ACTION_SET_ERROR = 'REDUX_SAGA_LOCATION_SET_ERROR';
export const REDUX_SAGA_LOCATION_ACTION_REQUEST = 'REDUX_SAGA_LOCATION_ACTION_REQUEST';
export const REDUX_SAGA_LOCATION_CLEAR_REQUEST = 'REDUX_SAGA_LOCATION_CLEAR_REQUEST';
export const REDUX_SAGA_LOCATION_STOP_REQUEST = 'REDUX_SAGA_LOCATION_STOP_REQUEST';
